### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by WolfePlays** [JohnHammond/msdt-follina#15]
When I do the python3 follina,py command I get this. `Traceback (most recent call last):
File "/home/user/msdt-follina/follina.py", line 8, in <module> import netifaces
ModuleNotFoundError: No module named 'netifaces'` Any help?

**Comment by feboyfierlyan** [comment]
you need to install the 'netifaces' modules first. You can install it like this : `pip install netifaces`. If you installing it in windows you probably have to install visual studio build tools, you can find it [here](https://visualstudio.microsoft.com/downloads/)

**Comment by WolfePlays** [comment]
@feboyfierlyan Thank you! but now I have an issues with the http.server. `/usr/bin/python: No module named http` Sorry if I look like a moron, trying to learn python and IT :)

**Comment by feboyfierlyan** [comment]
it's okay, everyone is learning :), with the issues you have, can i ask which python version do you use? because python3 has http inbuilt, but if accidentally deleted, it can be reinstalled using `pip3 install http` or `pip install http`

**Comment by WolfePlays** [comment]
I am on python 2.7.18 and python3 verison 3.9.2 when I did `pip3 install http/pip install http` it says

Defaulting to user installation because normal site-packages is not writeable
Collecting http
  Using cached http-0.02.tar.gz (32 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
 
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-n8xt_tpi/http_25b5d14cfb2e4ddd8ff717fa0cb76b69/setup.py", line 3, in <module>
          import http
        File "/tmp/pip-install-n8xt_tpi/http_25b5d14cfb2e4ddd8ff717fa0cb76b69/http/__init__.py", line 17, in <module>
          from request import Request
      ModuleNotFoundError: No module named 'request'
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by feboyfierlyan** [comment]
oh i kinda see what's the problem here, i see from the error log above `ModuleNotFoundError: No module named 'request'` you dont have _request_ module, that's kinda weird because python2 or python3 has request package built in, you have to install it. using `pip3 install requests` for python3 or `pip install requests` for python2. but i suggest you run the script in python3. let me know if any error still exist.

**Comment by WolfePlays** [comment]
After I did `pip3 install requests` this came up.
`Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in ./.local/lib/python3.9/site-packages (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./.local/lib/python3.9/site-packages (from requests) (1.25.11)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in ./.local/lib/python3.9/site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2020.6.20)
`

**Comment by WolfePlays** [comment]
Never Mind got it now it works. Thank you dude!

**Comment by feboyfierlyan** [comment]
Happy to hear that is working fine for you.
