### ISSUE TITLE
I can't run python 

~/msdt-follina $ python3 follina.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/msdt-follina/follina.py", line 8, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'

### ISSUE THREAD

**Issue by subnerf** [JohnHammond/msdt-follina#27]
~/msdt-follina $ python3 follina.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/msdt-follina/follina.py", line 8, in <module>
    import netifaces
ModuleNotFoundError: No module named 'netifaces'

**Comment by ElizabethHanson1999** [comment]
Hi 
Don't run it in virtual enviroment if you did so .

**Comment by Agent859** [comment]
Hi @subnerf 
Try `pip install netifaces`

**Comment by Morsmalleo** [comment]
Run `pip install netifaces`
