### ISSUE TITLE
The passkey

### ISSUE THREAD

**Issue by GamerAway** [JohnHammond/msdt-follina#29]
it was working well for a day after that there is no troubleshooting the passkey keep showing.
I reinstall the tool and the office but still the same.
I changed the default browser but still the same.
what to do next?

**Comment by erdalbucan** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/passoword-not-working-after-latest-update/1c295631-d8b5-4cb9-b9ed-701d53a79e10￼


> GamerAway ***@***.***> şunları yazdı (20.12.2022 19:39):
> 
> it was working well for a day after that there is no troubleshooting the passkey keep showing.
> I reinstall the tool and the office but still the same.
> I changed the default browser but still the same.
> what to do next?
> 
>

**Comment by GamerAway** [comment]
the problem is the new windows update they solve it XD
