### ISSUE TITLE
Can't use subdomains with -i option (ngrok)

### ISSUE THREAD

**Issue by Leo-Aqua** [JohnHammond/msdt-follina#7]
Command: 
```python3 follina.py -i 'https://c37d-2003-f4-2720-a380-5810-4952-ef4-2125.eu.ngrok.io'```
Output: 
```[!] error detering http hosting address. did you provide an interface or ip?```
Is there a way to fix this?

**Comment by fracool** [comment]
Hi Leo, re-read the help. The -i option sets the network interface, not the host name :)

**Comment by moamlrh** [comment]
I have the same issue "I can't set the ngrok IP without the port" 

btw the `-i` option is use to set the **interface** or the **IP** for ex: `-i eth0` or `-i 192.168.0.112`

**Comment by Mikusho** [comment]
If you want to use ngrok put on follina.py line 97

**Comment by toussoul** [comment]
can't we just set ngrok on the port provides

**Comment by toussoul** [comment]
can't we just set ngrok on the port provides
